export const exportService = {
  exportToCSV(data, filename = 'export') {
    if (!data || data.length === 0) {
      console.warn('No data to export');
      alert('No data to export!');
      return;
    }

    try {
      const headers = Object.keys(data[0] || {});
      const csvRows = [headers.join(',')];
      
      for (const row of data) {
        const values = headers.map(header => {
          let value = row[header];
          if (value === null || value === undefined) value = '';
          if (typeof value === 'object') value = JSON.stringify(value);
          return String(value).replace(/,/g, ';');
        });
        csvRows.push(values.join(','));
      }
      
      const blob = new Blob([csvRows.join('\n')], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${filename}.csv`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      console.log('CSV exported successfully');
    } catch (error) {
      console.error('Export failed:', error);
      alert('Export failed: ' + error.message);
    }
  },

  exportToJSON(data, filename = 'export') {
    if (!data) {
      console.warn('No data to export');
      return;
    }

    try {
      const json = JSON.stringify(data, null, 2);
      const blob = new Blob([json], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${filename}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      console.log('JSON exported successfully');
    } catch (error) {
      console.error('Export failed:', error);
    }
  },

  async exportToPDF(data, filename = 'export') {
    if (!data) {
      console.warn('No data to export');
      return;
    }

    try {
      // Simple HTML report
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>Defect Detection Report</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            h1 { color: #333; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #4CAF50; color: white; }
            .header { text-align: center; margin-bottom: 30px; }
            .date { color: #666; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Industrial Defect Detection Report</h1>
            <p class="date">Generated: ${new Date().toLocaleString()}</p>
          </div>
          <h2>Detection Summary</h2>
          <table>
            <thead>
              <tr><th>ID</th><th>Defect Type</th><th>Confidence</th><th>Severity</th><th>Status</th><th>Time</th></tr>
            </thead>
            <tbody>
              ${data.map(item => `
                <tr>
                  <td>${item.id || '-'}</td>
                  <td>${item.defect_type || '-'}</td>
                  <td>${((item.confidence_score || 0) * 100).toFixed(1)}%</td>
                  <td>${item.severity_level || '-'}</td>
                  <td>${item.is_rejected ? 'Rejected' : 'Accepted'}</td>
                  <td>${item.inspection_time ? new Date(item.inspection_time).toLocaleString() : '-'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <p style="margin-top: 30px; text-align: center; color: #666;">
            Generated by Industrial Defect Detection System
          </p>
        </body>
        </html>
      `;
      
      // Create blob and download
      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${filename}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      console.log('Report exported as HTML');
      alert('Report exported as HTML file!');
    } catch (error) {
      console.error('PDF export failed:', error);
      alert('Export failed: ' + error.message);
    }
  }
};